apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::005590229206:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1308W8QG6UBGU
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-25T08:52:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1183"
  uid: c0ef0d1d-0ed5-42c0-9186-f3674ab8e2cb
